In [4]:
import pandas as pd

In [2]:
import openpyxl as op
op.__version__

'3.1.5'

In [2]:
df=pd.read_clipboard()
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3

In [4]:
df=pd.read_csv('../../../data_colon.csv',delimiter=':')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [11]:
df=pd.read_excel('../../../Project-Management-Sample-Data.xlsx',engine='openpyxl',skiprows=5,usecols="b:h")
df  # To solve this Error commdand : pip install openpyxl

,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
0,Marketing,Market Research,Alice,2024-01-01,13,2024-01-14,0.78
1,Marketing,Content Creation,Bob,2024-01-14,14,2024-01-28,1.00
2,Marketing,Social Media Planning,Charlie,2024-01-28,22,2024-02-19,0.45
3,Marketing,Campaign Analysis,Daisy,2024-02-18,25,2024-03-14,0.00
4,Product Dev,Prototype Development,Ethan,2024-01-02,18,2024-01-20,1.00
5,Product Dev,Quality Assurance,Fiona,2024-01-20,10,2024-01-30,0.78
6,Product Dev,User Interface Design,Gabriel,2024-02-04,25,2024-02-29,0.00
7,Customer Svc,Service Improvement,Hannah,2024-02-01,22,2024-02-23,1.00
8,Customer Svc,Ticket Resolution,Ian,2024-02-24,25,2024-03-20,1.00
9,Customer Svc,Customer Feedback,Julia,2024-03-21,30,2024-04-20,0.00
10,Financial,Budget Analysis,Kevin,2024-02-02,22,2024-02-24,0.10
11,Financial,Financial Reporting,Mark,2024-02-13,21,2024-02-09,0.78
12,Financial,Investment Planning,Mark,2024-03-19,25,2024-04-13,1.00
13,Research,Market Trends Analysis,Nathan,2024-01-02,23,2024-01-25,0.50
14,Research,Data Collection,Olivia,2024-01-26,32,2024-02-27,0.00
15,Research,Research Paper Writing,Peter,2024-02-28,27,2024-03-26,0.00
16,Development,Software Development,Quinn,2024-01-02,36,2024-02-07,1.00
17,Development,Feature Enhancement,Rachel,2024-02-08,34,2024-03-13,0.00
18,Development,Code Review,Sam,2024-03-14,30,2024-04-13,0.00
19,Production,Manufacturing,Tim,2024-01-03,47,2024-02-19,0.30
20,Production,Quality Control,Ursula,2024-02-17,27,2024-03-15,0.00
21,Production,Packaging Design,Victor,2024-03-14,22,2024-04-05,0.00
22,Sales,Lead Generation,Wendy,2024-01-03,60,2024-03-03,0.70
23,Sales,Client Meetings,Xavier,2024-01-06,20,2024-01-26,0.78
24,Sales,Contract Negotiation,Yvette,2024-02-03,35,2024-03-09,0.00
25,Support,Technical Support,Zoe,2024-01-01,25,2024-01-26,1.00
26,Support,Bug Fixes,Aaron,2024-01-27,31,2024-02-27,1.00
27,Support,Software Updates,Bella,2024-03-02,22,2024-03-24,0.00
28,Operations,Process Optimization,Calvin,2024-01-03,30,2024-02-02,0.40
29,Operations,Inventory Management,Diane,2024-02-03,25,2024-02-28,0.00
30,Operations,Facility Maintenance,Edward,2024-02-29,20,2024-03-20,0.00
31,Consulting,Strategic Planning,Fiona,2024-01-02,35,2024-02-06,0.60
32,Consulting,Market Expansion,Gary,2024-02-02,32,2024-03-05,0.00
33,Consulting,Client Advisory,Helen,2024-03-06,25,2024-03-31,0.00
34,Training,Employee Training,Isaac,2024-01-04,27,2024-01-31,0.80
35,Training,Certification Programs,Jane,2024-01-28,30,2024-02-27,0.00
36,Training,Skill Development,Kyle,2024-02-28,22,2024-03-21,0.00
37,Events,Event Planning,Laura,2024-01-03,25,2024-01-28,0.30
38,Events,Conference Management,Mike,2024-02-03,20,2024-02-23,0.00
39,Events,Sponsorship Coordinatio,n Nancy,2024-02-24,35,2024-03-30,0.00
40,Logistics,Supply Chain Management,Oscar,2024-01-03,25,2024-01-28,0.50
41,Logistics,Transportation Planning,Patricia,2024-01-29,30,2024-02-28,1.00
42,Logistics,Inventory Optimization,Quentin,2024-03-29,20,2024-04-18,0.00
43,Engineering,Product Design,Rachel,2024-01-02,25,2024-01-27,0.20
44,Engineering,System Integration,Sam,2024-02-02,22,2024-02-24,0.00
45,Engineering,Prototype Testing,Tom,2024-02-23,27,2024-03-21,0.00