In [3]:
import pandas as pd

# Sampling 
- 1. under sampling df.sample(n=100)
- 2. Over Sampling

In [5]:
df=pd.read_csv('../../../car_data_500.csv')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
...,...,...,...,...,...,...,...,...,...
495,Toyota,18.9,6.0,1583,120,1918,11.3,79,India
496,Hyundai,16.5,4.0,3131,128,4312,13.1,77,US
497,Maruthi,24.8,4.0,3692,236,3951,12.5,79,US
498,Tata,12.2,4.0,1624,252,3795,9.1,79,South Korea
499,Honda,17.0,8.0,3408,110,3505,16.4,79,US

In [6]:
df.shape

(500, 9)

In [7]:
df.sample(n=100)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
257,Maruthi,11.7,4.0,3197,73,4184,10.8,74,Germany
274,BMW,22.1,4.0,2355,108,1925,14.7,77,Germany
464,Jaguar,14.8,4.0,4341,246,4335,15.4,79,India
155,Maruthi,18.5,4.0,2767,132,4216,8.9,76,South Korea
36,Tata,21.6,6.0,4192,181,2907,11.0,72,US
...,...,...,...,...,...,...,...,...,...
144,BMW,15.4,6.0,4037,267,4332,13.2,75,Japan
429,Audi,22.8,4.0,2631,263,2823,13.0,77,India
451,Toyota,21.6,6.0,3036,193,4468,14.1,70,Germany
186,Jaguar,17.4,8.0,1969,299,3427,10.7,70,Japan
72,Maruthi,21.7,4.0,2614,194,2950,7.5,77,Germany

In [8]:
df.sample(n=1000)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [9]:
df.sample(n=1000, replace=True)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
150,Ford,22.9,4.0,4706,208,4493,8.1,73,US
168,BMW,23.5,6.0,4909,96,2164,16.8,78,South Korea
177,Maruthi,17.5,4.0,3450,223,2140,16.4,78,US
369,Honda,23.4,4.0,4671,245,2790,10.0,76,Japan
130,Audi,16.1,4.0,1722,109,3922,11.4,79,Japan
...,...,...,...,...,...,...,...,...,...
164,Toyota,13.3,6.0,3396,171,3101,10.1,76,South Korea
370,Hyundai,24.9,4.0,2036,227,3064,13.6,78,South Korea
172,BMW,17.9,8.0,3485,166,2746,12.5,79,Japan
135,Honda,22.7,4.0,4673,77,4295,11.1,73,US
283,Toyota,24.9,6.0,2021,288,4111,12.6,71,Germany